const State = 
[
  "Andaman And Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  // "Karnatak",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Mumbai (Maharashtra)",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
]

const Constituency = 

{
    "Andaman And Nicobar Islands": [
      "Andaman Nicobar"
    ],

    "Andhra Pradesh": [
      "Amalapuram",
      "Anakapalli",
      "Anantapur",
      "Araku",
      "Bapatla",
      "Chittoor",
      "Eluru",
      "Guntur",
      "Hindupur",
      "Kadapa",
      "Kakinada",
      "Kurnool",
      "Machilipatnam",
      "Nandyal",
      "Narasaraopet",
      "Narsapuram",
      "Nellore",
      "Ongole",
      "Rajahmundry",
      "Rajampet",
      "Srikakulam",
      "Tirupati",
      "Vijayawada",
      "Visakhapatnam",
      "Vizianagaram"
    ],

    "Arunachal Pradesh": [
      "Arunachal East",
      "Arunachal West"
    ],

    "Assam": [
      "Autonomous District",
      "Barpeta",
      "Dhubri",
      "Dibrugarh",
      "Gauhati",
      "Jorhat",
      "Kaliabor",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Mangaldoi",
      "Nowgong",
      "Silchar",
      "Tezpur"
    ],

    "Bihar": [
      "Araria",
      "Arrah",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Buxar",
      "Darbhanga",
      "Gaya",
      "Gopalganj",
      "Hajipur",
      "Jahanabad",
      "Jamui",
      "Jhanjharpur",
      "Karakat",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Madhepura",
      "Madhubani",
      "Maharajganj",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Paschim Champaran",
      "Pataliputra",
      "Patna Sahib",
      "Purnia",
      "Purvi Champaran",
      "Samastipur",
      "Saran",
      "Sasaram",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Ujiarpur",
      "Vaishali",
      "Valmiki Nagar"
    ],

    "Chandigarh": [
      "Chandigarh"
    ],

    "Chhattisgarh": [
      "Bastar",
      "Bilaspur",
      // "Daman and Diu",
      "Durg",
      "Janjgir–Champa",
      "Kanker",
      "Korba",
      "Mahasamund",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Surguja"
    ],

    "Dadra and Nagar Haveli and Daman and Diu": [
      "Dadra Nagar Haveli",
      "Daman and Diu"
    ],

    "Delhi": [
      "Chandani Chowk",
      "East Delhi",
      "New Delhi",
      "North East Delhi",
      "North West Delhi",
      "South Delhi",
      "West Delhi"
    ],

    "Goa": [
      "North Goa",
      "South Goa"
    ],

    "Gujarat": [
      "Ahmedabad East",
      "Ahmedabad West",
      "Amreli",
      "Anand",
      "Banaskantha",
      "Bardoli",
      "Bharuch",
      "Bhavnagar",
      "Chhota Udaipur",
      "Dahod",
      "Gandhinagar",
      "Jamnagar",
      "Junagarh",
      "Kachchh",
      "Kheda",
      "Mehsana",
      "Navsari",
      "Panchmahal",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surat",
      "Surendranagar",
      "Vadodara",
      "Valsad"
    ],

    "Haryana": [
      "Ambala",
      "Bhiwani–Mahendragarh",
      "Faridabad",
      "Gurgaon",
      "Hissar",
      "Karnal",
      "Kurukshetra",
      "Rohtak",
      "Sirsa",
      "Sonipat"
    ],

    "Himachal Pradesh": [
      "Hamirpur",
      "Kangra",
      "Mandi",
      "Shimla"
    ],

    "Jammu and Kashmir": [
      "Anantnag",
      "Baramulla",
      "Jammu",
      "Srinagar",
      "Udhampur"
    ],

    "Jharkhand": [
      "Chatra",
      "Dhanbad",
      "Dumka",
      "Giridih",
      "Godda",
      "Hazaribagh",
      "Jamshedpur",
      "Khunti",
      "Kodarma",
      "Lohardaga",
      "Palamu",
      "Rajmahal",
      "Ranchi",
      // "Ranchi",
      "Singhbhum"
    ],

    // "Karnatak": [

    // ],

    "Karnataka": [
      "Bagalkot",
      "Bangalore Central",
      "Bangalore North",
      "Bangalore Rural",
      "Bangalore South",
      "Belagavi",
      "Bellary",
      "Bidar",
      "Bijapur",
      "Chamrajanagar",
      "Chikballapur",
      "Chikkodi",
      "Chitradurga",
      "Dakshina Kannada",
      "Davanagere",
      "Dharwad",
      "Hassan",
      "Haveri",
      "Kalaburagi",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysore",
      "Raichur",
      "Shimoga",
      "Tumkur",
      "Udupi Chikmagalur",
      "Uttara Kannada"
    ],

    "Kerala": [
      "Alappuzha",
      "Alathur",
      "Attingal",
      "Chalakudy",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Mavelikara",
      "Palakkad",
      "Pathanamthitta",
      "Ponnani",
      "Thiruvananthapuram",
      "Thrissur",
      "Vatakara",
      "Wayanad"
    ],

    "Ladakh": [
      "Ladakh"
    ],

    "Lakshadweep": [
      "Lakshadweep"
    ],

    "Madhya Pradesh": [
      "Balaghat",
      "Betul",
      "Bhind",
      "Bhopal",
      "Chhindwara",
      "Damoh",
      "Dewas",
      "Dhar",
      "Guna",
      "Gwalior",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Khajuraho",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Shahdol",
      "Sidhi",
      "Tikamgarh",
      "Ujjain",
      "Vidisha"
    ],

    "Maharashtra": [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Baramati",
      "Beed",
      "Bhandara–Gondiya",
      "Bhiwandi",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Dindori",
      "Gadchiroli–Chimur",
      "Hatkanangale",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kalyan",
      "Kolhapur",
      "Latur",
      "Madha",
      "Maval",
      "Mumbai North",
      "Mumbai North–Central",
      "Mumbai North–East",
      "Mumbai North–West",
      "Mumbai South",
      "Mumbai South–Central",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ramtek",
      "Ratnagiri–Sindhudurg",
      "Raver",
      "Sangli",
      "Satara",
      "Shirdi",
      "Shirur",
      "Solapur",
      "Thane",
      "Wardha",
      "Yavatmal–Washim"
    ],
    "Mumbai (Maharashtra)" : [
      "Mumbai North",
      "Mumbai North–Central",
      "Mumbai North–East",
      "Mumbai North–West",
      "Mumbai South",
      "Mumbai South–Central",
    ],

    "Manipur": [
      "Inner Manipur",
      "Outer Manipur"
    ],

    "Meghalaya": [
      "Shillong",
      "Tura"
    ],

    "Mizoram": [
      "Mizoram"
    ],

    "Nagaland": [
      "Nagaland"
    ],

    "Odisha": [
      "Aska",
      "Balasore",
      "Bargarh",
      "Berhampur",
      "Bhadrak",
      "Bhubaneswar",
      "Bolangir",
      "Cuttack",
      "Dhenkanal",
      "Jagatsinghur",
      "Jajpur",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Keonjhar",
      "Koraput",
      "Mayurbhanj",
      "Nabarangpur",
      "Puri",
      "Sambalpur",
      "Sundargarh"
    ],

    "Puducherry": [
      "Puducherry"
    ],

    "Punjab": [
      "Amritsar",
      "Anandpur Sahib",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Firozpur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Khadoor Sahib",
      "Ludhiana",
      "Patiala",
      "Sangrur"
    ],

    "Rajasthan": [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Barmer",
      "Bharatpur",
      "Bhilwara",
      "Bikaner",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Ganganagar",
      "Jaipur",
      "Jaipur Rural",
      "Jalore",
      "Jhalawar–Baran",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli–Dholpur",
      "Kota",
      "Nagaur",
      "Pali",
      "Rajsamand",
      "Sikar",
      "Tonk–Sawai Madhopur",
      "Udaipur"
    ],

    "Sikkim": [
      "Sikkim"
    ],

    "Tamil Nadu": [
      "Arakkonam",
      "Arani",
      "Chennai Central",
      "Chennai North",
      "Chennai South",
      "Chidambaram",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kallakurichi",
      "Kancheepuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Mayiladuthurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pollachi",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Sriperumbudur",
      "Tenkasi",
      "Thanjavur",
      "Theni",
      "Thiruvallur",
      "Thoothukudi",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tiruppur",
      "Tiruvannamalai",
      "Vellore",
      "Viluppuram",
      "Virudhunagar"
    ],

    "Telangana": [
      "Adilabad",
      "Bhongir",
      "Hyderabad",
      "Karimnagar",
      "Khammam",
      "Mahabubabad",
      "Mahbubnagar",
      "Malkajgiri",
      "Medak",
      "Nagarkurnool",
      "Nalgonda",
      "Nizamabad",
      "Peddapalle",
      "Secunderabad",
      "Warangal",
      "Zahirabad"
    ],

    "Tripura": [
      "Tripura East",
      "Tripura West",
    ],

    "Uttar Pradesh": [
      "Agra",
      "Akbarpur",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Aonla",
      "Azamgarh",
      "Badaun",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Banda",
      "Bansgaon",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Bulandshahr",
      "Chandauli",
      "Deoria",
      "Dhaurahra",
      "Domariyaganj",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Fatehpur Sikri",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Ghosi",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kairana",
      "Kaiserganj",
      "Kannauj",
      "Kanpur Urban",
      "Kaushambi",
      "Kheri",
      "Kushi Nagar",
      "Lalganj",
      "Lucknow",
      "Machhlishahr",
      "Maharajganj",
      "Mainpuri",
      "Mathura",
      "Meerut",
      "Mirzapur",
      "Misrikh",
      "Mohanlalganj",
      "Moradabad",
      "Muzaffarnagar",
      "Nagina",
      "Phulpur",
      "Pilibhit",
      "Pratapgarh",
      "Rae Bareli",
      "Rampur",
      "Robertsganj",
      "Saharanpur",
      "Salempur",
      "Sambhal",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shrawasti",
      "Sitapur",
      "Sultanpur",
      "Unnao",
      "Varanasi"
    ],

    "Uttarakhand": [
      "Almora",
      "Garhwal",
      "Haridwar",
      // "Haridwar",
      // "Haridwar",
      "Nainital–Udhamsingh Nagar",
      "Tehri Garhwal"
    ],

    "West Bengal": [
      "Alipurduars",
      "Arambag",
      "Asansol",
      "Baharampur",
      "Balurghat",
      "Bangaon",
      "Bankura",
      "Barasat",
      "Bardhaman Purba",
      "Bardhaman–Durgapur",
      "Barrackpur",
      "Basirhat",
      "Birbhum",
      "Bishnupur",
      "Bolpur",
      "Cooch Behar",
      "Darjeeling",
      "Diamond Harbour",
      "Dum Dum",
      "Ghatal",
      "Hooghly",
      "Howrah",
      "Jadavpur",
      "Jalpaiguri",
      "Jangipur",
      "Jaynagar",
      "Jhargram",
      "Kanthi",
      "Kolkata Dakshin",
      "Kolkata Uttar",
      "Krishnanagar",
      "Maldaha Dakshin",
      "Maldaha Uttar",
      "Mathurapur",
      "Medinipur",
      "Murshidabad",
      "Purulia",
      "Raiganj",
      "Ranaghat",
      "Sreerampur",
      "Tamluk",
      "Uluberia"
    ]
  }

  export {
    State,
    Constituency
  }